import { Toaster } from "@/components/ui/sonner";
import Theme from "@/context/ThemeContext";
import { ABeeZee } from "@next/font/google";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import "../globals.css";
import Sidebar from "@/components/sidebar/Sidebar";

const abeezee = ABeeZee({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Sentiments Analysis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${abeezee.className} dark:bg-background text-primary w-screen h-screen overflow-hidden`}
        suppressHydrationWarning
      >
        <NextIntlClientProvider>
          <Theme>
            <Sidebar>
              <main className="overflow-x-hidden">{children}</main>
              <Toaster />
            </Sidebar>
          </Theme>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
